### ISSUE TITLE
玉転がし制作日記 1日目

### ISSUE THREAD

**Issue by vjsigsig** [vjsigsig/dev_unity#2]
前置き
=====================================
+ なんかUnityってやつ流行ってんな。やってみっか
+ クライアントの仕組みも、C#も一切知らない状態
+ っていうかぶっちゃけUnityを説明しろ　って言われても説明できない状態から開始している

1日目
=====================================
## Unityをインストール
+ 公式サイトからクライアントをインストールしてみた
+ 家の回線がゴミクズ過ぎて10分経って10％くらいのアップデート進捗度
+ 晩飯を食う、ジムに行く、帰宅して風呂、食器を片付ける
+ ようやくアップデート完了
![image](https://cloud.githubusercontent.com/assets/9949165/20488875/f91cc5f4-b04b-11e6-81c9-2130c6495ffb.png)
**あ？なんでサインインする必要があんのよ**
+ よくわかんね。寝よ
+ 1日目終了

**Comment by ike-jp** [comment]
- 最初だけ必須ぽい？
- 定期的に認証処理が動く
- 無視しても未ログイン状態でいじれる
- 未ログイン状態でいじってると定期的にいきなり認証ウィンドウ出て困る
- アセットストアを利用する場合はログイン必須
